- phospho/integrations.py
- phospho/testing.py
- pyproject.toml
This makes the package smaller if you only use it for logging.
> Make pandas import optional

- README.md
> docs(readme): Update README.md with installation and usage instructions

- backend/app/services/mongo/explore.py
- backend/app/services/mongo/metadata.py
- platform/app/org/insights/metadata/page.tsx
- platform/app/org/users/[id]/sessions/page.tsx
- platform/app/org/users/[id]/tasks/page.tsx
- platform/app/org/users/page.tsx
- platform/components/fetch-data/fetch-org-project.tsx
- platform/components/insights/events/success-rate-by-event.tsx
- platform/components/transcripts/sessions/session-dataviz.tsx
- platform/components/transcripts/sessions/session.tsx
- platform/components/transcripts/tasks/tasks-dataviz.tsx
- Deduplicate top event counts (A task can have the same event assigned to it, multiple times)
- Fix Sessions length histogram
- Adds more data caching for smoother UX
> Deduplicate top events

- backend/app/api/platform/endpoints/tasks.py
- backend/app/api/platform/models/__init__.py
- backend/app/api/platform/models/tasks.py
- backend/app/db/mongo.py
- backend/app/services/mongo/explore.py
- backend/app/services/mongo/metadata.py
- backend/app/services/mongo/projects.py
- backend/app/services/mongo/tasks.py
- extractor/app/services/pipelines.py
- internal-tools/cronemails/db.py
- platform/app/org/insights/kpis/page.tsx
- platform/components/fetch-data/fetch-tasks-sessions.tsx
- platform/components/task-box.tsx
- platform/components/transcripts/sessions/session-dataviz.tsx
- platform/components/transcripts/sessions/session.tsx
- platform/components/transcripts/tasks/task.tsx
- platform/components/transcripts/tasks/tasks-dataviz.tsx
- Adds event manual annotation 
- Remove unneeded $lookup in queries
> Adds event annotation

- .env.example
- README.md
- backend/app/main.py
- extractor/app/main.py
- extractor/app/services/log.py
- phospho-python/phospho/config.py
- phospho-python/phospho/lab/job_library.py
- Added support for custom LLM providers
- Quadrant dependency is now optional
> Added support for custom LLM providers

- phospho-python/phospho/models.py
- platform/app/org/insights/events/page.tsx
- platform/components/fetch-data/fetch-tasks-sessions.tsx
- platform/components/insights/events/create-event.tsx
- platform/components/insights/events/event-list.tsx
Edited events stay at the same place in the list
> Easier state management for events tab

- backend/app/api/v2/endpoints/backfill.py
- backend/app/api/v2/endpoints/projects.py
- backend/app/api/v2/models/__init__.py
- backend/app/api/v2/models/batckfill.py
- backend/app/main.py
Users can now upload batches of historical tasks
> Added backfill option

- platform/components/navbar/create-project-button.tsx
- platform/components/navbar/project.tsx
- platform/components/navbar/select-project-dropdown.tsx
> Move Create project button out of dropdown 

- platform/app/org/insights/metadata/page.tsx
- platform/store/store.ts
Increase size of graph and add ease of life features
> Improve Metadata tab

- backend/app/api/platform/endpoints/explore.py
- backend/app/api/platform/endpoints/metadata.py
- backend/app/api/platform/endpoints/projects.py
- backend/app/services/mongo/explore.py
- backend/app/services/mongo/metadata.py
- backend/app/services/mongo/projects.py
- backend/app/services/mongo/tasks.py
- platform/app/org/insights/metadata/page.tsx
- platform/components/filters.tsx
- platform/components/transcripts/tasks/tasks-dataviz.tsx
- platform/components/transcripts/tasks/tasks-table.tsx
- platform/models/models.ts
- platform/store/store.ts
> Adds metadata filter to the Tasks tab

- backend/app/services/mongo/events.py
- backend/app/services/mongo/sessions.py
- backend/app/services/mongo/tasks.py
And confirmed events keeps their source
> Events labeled by humans are marked as confirmed

- platform/components/callouts/import-data.tsx
- platform/components/navbar/create-project-button.tsx
> fix: create project

- platform/Dockerfile-porter
- platform/app/onboarding/customize/[id]/add-events.tsx
- platform/next.config.js
- platform/package-lock.json
> ts-ignore on phospho and new dockerfile for the platfom

- platform/middleware.ts
Ref : https://docs.propelauth.com/reference/fullstack-apis/nextjsapp/installation-and-setup#setup-the-next-js-library
> Adds propelauth middleware

- platform/app/layout.tsx
- platform/components/IntercomClientComponent.tsx
Intercom integration in the platform
> Intercom integration

- phospho-python/phospho/lab/language_models.py
- phospho-python/pyproject.toml
- Add together provider
- fix solar url
> feat: Add together provider

- phospho-python/phospho/lab/language_models.py
- phospho-python/pyproject.toml
- add anyscale and fireworks provider to the lab
- update phospho version to 0.3.25
> feat: add anyscale and fireworks provider

- backend/app/db/mongo.py
- backend/app/services/mongo/tasks.py
- extractor/app/main.py
- extractor/app/services/log.py
- extractor/app/services/tasks.py
- phospho-python/phospho/models.py
- platform/components/insights/events/create-event.tsx
- platform/components/transcripts/tasks/task.tsx
- platform/models/models.ts
- Adds last task event detection
- Remove qdrant init
- Remove embeddings computation
> feat: Adds event detection only on last task of a session

- platform/components/argilla/create-argilla-dataset.tsx
Added default cool name generator for datasets, disabled create dataset button while waiting for server response.
> name generator for datasets, disabled create dataset button while waiting for server response

- backend/app/core/config.py
- backend/app/security/authentification.py
- backend/app/services/mongo/explore.py
- backend/notebooks/test_flattened_task_endpoints.ipynb
- phospho-python/phospho/models.py
- platform/README.md
- Add event information in tasks_df
- Improve docs
> feat: Add event information in tasks_df

- backend/app/services/mongo/explore.py
- phospho-python/phospho/models.py
- Add event_source in the endpoint FlattenedTask
> feat: Add event_source in the endpoint FlattenedTask

- phospho-python/phospho/__init__.py
- phospho-python/phospho/client.py
- Now removed events are accessible with the task_df function
> feat: Add removed_events in the task_df function

- backend/app/services/mongo/explore.py
- extractor/README.md
- phospho-python/phospho/models.py
- platform/components/insights/events/event-analytics.tsx
- Add event scores in the frontend
- Add the computation of F1-score, precision, recall in the event metrics
> feat: Add event scores

- backend/app/api/platform/endpoints/sessions.py
- backend/app/services/mongo/sessions.py
- platform/components/insights/events/event-analytics.tsx
- platform/components/label-events.tsx
- Add dropdown menu options to change class and score in sessions
- Fix the Add event problem in sessions
> feat: Add dropdown menu options to change class and score in sessions

- platform/app/page.tsx
- platform/components/abtesting/abtesting.tsx
- platform/components/abtesting/create-new-ab-test-button.tsx
- Clicking top left phospho redirects now to /sessions
- Fix wording in AB test tab
> Fix: Minor fixes

- backend/app/api/platform/endpoints/organizations.py
- backend/app/api/platform/models/__init__.py
- backend/app/api/platform/models/organizations.py
- backend/app/core/config.py
- backend/poetry.lock
- backend/pyproject.toml
> feat: Sync user creation data with customer data platform

- backend/app/services/mongo/explore.py
- platform/components/insights/events/event-analytics.tsx
- Create two different metric f1 etc for multiclass events and binary events
> fix: Event analytics page

- platform/components/task-box.tsx
> feat: Add special visualization of metadata.system_prompt

- platform/components/filters.tsx
- platform/components/insights/clusters/clusters-sheet.tsx
- platform/components/insights/clusters/clusters-table-columns.tsx
- platform/components/insights/clusters/clusters-table.tsx
- platform/components/insights/clusters/clusters.tsx
This opens the configure clustering detection sheet with a default filter
> feat: Adds pickaxe tool in clustering

- backend/app/api/v2/endpoints/log.py
- backend/app/services/backtest.py
- backend/app/services/mongo/extractor.py
- backend/app/services/mongo/files.py
> fix: Ignore intermediate_inputs

- platform/package-lock.json
- platform/package.json
Axios was not used anymore in the platform
> platform: deleted axios dependency, updated phospho package

- backend/app/api/platform/endpoints/projects.py
- backend/app/services/mongo/files.py
- platform/app/onboarding/create-project/page.tsx
- platform/app/onboarding/customize/[id]/add-events.tsx
- platform/app/onboarding/page.tsx
- platform/app/onboarding/survey/about-you.tsx
- platform/components/callouts/import-data.tsx
- platform/components/navbar/help.tsx
- platform/lib/utils.ts
- Skip the welcome screen for onboarding
- Adds default project name
- Wording
> feat: Simplify onboarding, show support for user_id in import file, improve upload file box

- phospho-python/phospho/integrations.py
- phospho-python/pyproject.toml
- Don't log intermediate outputs
- Let the user specify the inputs and outputs key
- More complete wrapper of the phospho base module
> feat: Update the langchain callback

- backend/app/services/mongo/explore.py
- backend/app/services/mongo/tasks.py
- platform/app/org/insights/clusters/[id]/page.tsx
- platform/components/insights/clusters/clusters.tsx
- platform/components/transcripts/sessions/session-dataviz.tsx
- Running a clustering on an empty project (no clustering) didn't display progress bar
- Sessions "import data" was not displayed"
> Fix: frontend issues

- extractor/app/services/log/base.py
- Fetch the token nbr data directly in the request
- better error handling
> fix: get_nb_completions_tokens

- platform/app/org/settings/project/page.tsx
- platform/app/org/transcripts/sessions/[id]/page.tsx
- platform/components/sessions/session-preview.tsx
- platform/components/sessions/session.tsx
- platform/components/sessions/sessions-table-columns.tsx
- platform/components/sessions/sessions-table.tsx
- platform/components/tasks/task-preview.tsx
- platform/components/tasks/task.tsx
- platform/components/tasks/tasks-table-columns.tsx
- platform/components/tasks/tasks-table.tsx
- platform/components/ui/resizable.tsx
- platform/package-lock.json
- platform/package.json
- platform/store/store.ts
- Adds side pannel preview for Session, Task
- Removes "Evaluate and show next"
> feat: Adds side panel preview for Sessions, Tasks

- backend/app/services/mongo/organizations.py
- platform/components/navbar/select-project-dropdown.tsx
- platform/components/projects/create-project-form.tsx
- Add a suffix if the project name already exists
- fix: Dropdown selection project
> feat: Unique project name

- platform/components/callouts/import-data.tsx
> fix: Enlarge drag and drop zone 

- backend/app/services/mongo/explore.py
- backend/app/services/mongo/projects.py
- backend/app/services/mongo/tasks.py
> feat: Faster daily graphs

- backend/app/api/v2/endpoints/triggers.py
> feat: Adds all projects internal computation

- backend/app/api/platform/endpoints/projects.py
- backend/app/api/platform/models/__init__.py
- backend/app/api/platform/models/explore.py
- backend/app/services/mongo/explore.py
- backend/app/services/mongo/metadata.py
- backend/app/services/mongo/projects.py
- backend/app/services/mongo/tasks.py
- platform/app/org/transcripts/users/[user_id]/layout.tsx
- platform/app/org/transcripts/users/page.tsx
- platform/components/users/user-preview.tsx
- platform/components/users/users-table-columns.tsx
- platform/components/users/users-table.tsx
The date filters were applied on the opened side panel in Users tab, which resulted in missing messages sometimes
- Date filters added in side panel
- Temporary date filter on user page (not effective yet)
> feat: Adds Date filter in User side pannel

- backend/app/api/platform/endpoints/explore.py
- backend/app/api/platform/endpoints/metadata.py
- backend/app/api/platform/endpoints/projects.py
- backend/app/api/platform/models/__init__.py
- backend/app/api/platform/models/explore.py
- backend/app/api/v2/models/projects.py
- backend/app/services/mongo/explore.py
- backend/app/services/mongo/metadata.py
- backend/app/services/mongo/projects.py
- backend/app/services/mongo/query_builder.py
- backend/tests/services/test_explore.py
- platform/components/callouts/setup-users.tsx
- platform/components/table-navigation.tsx
- platform/components/users/user-preview.tsx
- platform/components/users/users-dataviz.tsx
- platform/components/users/users-table-columns.tsx
- platform/components/users/users-table.tsx
- platform/models/models.ts
- platform/store/store.ts
Filters didn't work for users tab
optimized users querying
> feat: Add filtering to user tab

- backend/app/services/mongo/metadata.py
- platform/components/users/users-table-columns.tsx
Issues with None
Better column headers && filtering
> Fix: user querying

- backend/app/services/mongo/metadata.py
> Fix: success rate in user panel

- backend/app/services/mongo/metadata.py
> Fix: session length in users

- platform/components/users/users-table-columns.tsx
> Fix: sorting

- backend/app/services/mongo/dataviz.py
- platform/app/org/dataviz/studio/page.tsx
- platform/components/dataviz.tsx
- Better handling of dataviz sizes (in the dashboard, in the studio)
- Fixed an issue with metadata fields
> style: Flip charts for time series graph

- platform/components/sessions/sessions-table.tsx
- platform/components/tasks/tasks-table.tsx
- platform/components/users/users-table.tsx
> style: Highlight selected row in table

- backend/app/api/platform/endpoints/explore.py
- backend/app/api/platform/models/clusters.py
- backend/app/services/mongo/ai_hub.py
- backend/app/services/mongo/clustering.py
- backend/app/services/mongo/explore.py
- backend/app/services/mongo/predict.py
- extractor/extractor/services/pipelines.py
> Fix: Chat billing

- extractor/extractor/services/sentiment_analysis.py
> fix: crop sentiment & language inputs

- backend/app/api/v3/models/run.py
- backend/app/services/mongo/extractor.py
- extractor/extractor/models/__init__.py
- extractor/extractor/models/pipelines.py
- extractor/extractor/services/pipelines.py
- extractor/extractor/services/projects.py
- extractor/extractor/temporal/activities.py
- extractor/extractor/temporal/workflows.py
> Fix: main pipeline types

- backend/app/api/platform/endpoints/organizations.py
- backend/app/api/platform/models/__init__.py
- backend/app/api/platform/models/organizations.py
- backend/app/db/mongo.py
- backend/app/services/mongo/organizations.py
- platform/app/org/settings/billing/page.tsx
- platform/components/sessions/session-dataviz.tsx
- platform/components/settings/usage-graph.tsx
> feat: Adds usage overview

- backend/app/services/mongo/organizations.py
> fix: Better support empty billing overview

- backend/app/api/platform/models/integrations.py
> Fix issue with argilla endpoint

- backend/app/services/mongo/clustering.py
- backend/app/services/mongo/projects.py
- backend/tests/integration/python/test_onboarding.py
- platform/components/clusters/clusters.tsx
Before, the clustering bar was not displayed on the first clustering of a project.
Now it is.
> fix: Clustering loading bar

- platform/components/search-bar.tsx
- platform/components/users/users-table.tsx
Pagination didn't work because Searchbar useEffect hook kept resetting pagination
Works as intended
> fix: Pagination not working

- backend/app/services/log.py
- backend/app/services/mongo/extractor.py
- extractor/extractor/models/log.py
- extractor/extractor/services/log/tasks.py
- extractor/extractor/temporal/activities.py
- platform/components/search-bar.tsx
> fix: Sessions processing

- platform/package-lock.json
- platform/package.json
> fix: issue with user id filters & chore: update deps

- platform/package-lock.json
- platform/package.json
> chore: increase max input size for user ids

- backend/poetry.lock
- phospho-python/pyproject.toml
> chore: Update python version

- backend/app/services/integrations/opentelemetry.py
- phospho-python/phospho/models.py
- platform/app/org/dataviz/studio/page.tsx
- platform/components/dashboard/dashboard.tsx
- platform/components/dataviz.tsx
- platform/models/models.ts
> feat: Save filters in viz in dashboard

- backend/app/api/platform/endpoints/explore.py
- backend/app/services/mongo/events.py
- backend/app/services/mongo/explore.py
- platform/app/org/insights/events/[id]/page.tsx
- platform/app/org/insights/metadata/page.tsx
- platform/app/org/insights/topics/page.tsx
- platform/components/events/event-analytics.tsx
Issues with getting the EventDefinition
More straightforward code
Tasks table in event page
> feat: Display a Tasks table on event page

- backend/app/api/v2/endpoints/triggers.py
- backend/app/db/mongo.py
> feat: Sync SQL trigger

- backend/app/services/mongo/explore.py
> Fix: data type

- backend/app/services/mongo/explore.py
> Fix df export error

- platform/app/org/dataviz/studio/page.tsx
- platform/components/dataviz.tsx
> feat: Adds dataviz download

- backend/app/api/v2/endpoints/triggers.py
- backend/app/services/mongo/explore.py
> Fix: trigger & graph 

- backend/app/api/v2/endpoints/triggers.py
> Fix trigger

- backend/app/api/platform/endpoints/events.py
- backend/app/api/v3/endpoints/log.py
- backend/app/services/mongo/projects.py
- platform/components/users/users-dataviz.tsx
> fix: user dataviz

- backend/app/api/platform/endpoints/recipes.py
- platform/app/checkout/thank-you/page.tsx
- platform/components/run-analysis-past.tsx
> style: better error toast

- backend/app/services/mongo/projects.py
- backend/app/services/mongo/users.py
- platform/components/users/users-table-columns.tsx
Category event were all grouped together
There are separeted by label
> FEAT: Improve users table for categorical event

- backend/Dockerfile
- extractor/Dockerfile
> remove: unused docker command

- platform/app/org/dataviz/studio/page.tsx
> Fix: More optim for data studio

- backend/app/services/mongo/sessions.py
> fix: Optimize fetch sessions

- backend/app/services/mongo/tasks.py
> fix: Optimize fetch tasks

- backend/app/db/mongo.py
- backend/app/services/integrations/postgresql.py
- backend/app/services/mongo/tasks.py
> feat: Adds job results index

- backend/app/services/integrations/postgresql.py
> Fix: sql export

- backend/app/services/integrations/postgresql.py
- backend/app/services/mongo/tasks.py
- backend/scripts/create_temp_table.ipynb
- phospho-python/phospho/models.py
The table was created by pandas which resulted in missing columns
- Create table before manually (still doesn't work) with the right types
- Support for better data types in postgresql export
> Fix: Edits to sql integration

- platform/package-lock.json
- platform/package.json
> fix: Revert Next version

- backend/phospho_backend/services/mongo/emails.py
- backend/phospho_backend/services/mongo/projects.py
- internal-tools/cronemails/email_event.py
> Fix: email users

- .github/workflows/phospho-python-test.yaml
- backend/phospho_backend/api/platform/endpoints/projects.py
- backend/phospho_backend/api/platform/models/projects.py
- backend/phospho_backend/services/mongo/clustering.py
- backend/phospho_backend/services/mongo/projects.py
- phospho-python/phospho/models.py
- platform/components/clusters/clusters.tsx
- platform/components/clusters/download-clusterings.tsx
I added a button in the Clusterings to exports clusterings data
> Feat : Export Clusterings Data

- .github/workflows/backend-deploy-production.yml
- [ x] typing, linting, docstrings (cicd will fail)
> Update backend-deploy-production.yml to change min-instances
