.github/workflows/test.yaml, docs/source/apidocs/phospho/phospho.md, docs/source/apidocs/phospho/phospho.utils.md, poetry.lock, pyproject.toml
Also make a bunch of dep optional and adds poetry.lock
Change group names `test` -> `dev`
=> (Python 3.8 support) Update dependencies to increase compatibility 

phospho/consumer.py
If you enable debug logging, you get a log "Batch: []" every tick, which hangs the event loop in notebooks and is annoying in prod settings. This removes it.
=> Remove debug log every tick

backend/Dockerfile-porter
We install phospho python from pip, not through a local install
=> Added a Porter specific Dockerfile

backend/app/api/platform/endpoints/explore.py
Keeps the arguments the same way, since the filters in ai-hub and platform/detect-clusters are the same
=> Remove rounding of timestamps

extractor/app/temporal/workflows.py
temporary fix, need to find root cause of issue
__mro_entries__ on threading.local restricted
Task exception was never retrieved
future: <Task finished name='Task-2286 (workflow: run_process_log_for_tasks_workflow, id: 53a63333f89348279708631deb467424, run: f8a1572e-f8d1-46b5-b1aa-2a92082f69be)' coro=<AsyncClient.aclose() done, defined at /src/.venv/lib/python3.11/site-packages/httpx/_client.py:2011> exception=RestrictedWorkflowAccessError('Cannot access threading.local.__mro_entries__ from inside a workflow. If this is code from a module not used in a workflow or known to only be used deterministically from a workflow, mark the import as pass through.')>
=> fix: __mro_entries__ on threading.local restricted

backend/app/services/mongo/ai_hub.py, backend/app/services/mongo/extractor.py, extractor/README.md, extractor/app/temporal/workflows.py, platform/components/insights/clusters/clusters-cards.tsx
Don't wait for the return values
https://github.com/uber-go/cadence-client/issues/866
+ Various fixes
=> Fix: Use start_workflow instad of execute_workflow in extractor

backend/app/api/platform/endpoints/explore.py, platform/app/org/ab-testing/[id]/page.tsx, platform/app/org/insights/clusters/[id]/page.tsx, platform/components/clusters/clusters-cards.tsx, platform/components/events/event-analytics.tsx
Couldn't get the filter resetting to work on component unmount without getting infinite re-renders, associating them to back button as a temporary fix
=> fix: infinite renders when exploring cluster/explore A/B test

.github/pull_request_template.md
=> Feat: Adds a PR template

backend/app/api/v2/models/projects.py, backend/app/services/mongo/metadata.py, platform/app/org/settings/project/page.tsx, platform/components/clusters/clusters.tsx, platform/components/interactive-datetime.tsx, platform/components/sessions/sessions-table-columns.tsx, platform/components/tasks/tasks-table-columns.tsx, platform/components/users/users-table-columns.tsx, platform/lib/time.ts, platform/models/models.ts, platform/package-lock.json, platform/package.json
Hard to read dates, no activity info for users
- Interactive date display component, with different level of information
- Last message and first message dates of users
- Project creation date and interactive cluster date
=> feat: Adds last message and first message

.github/workflows/autopr.yml, platform/app/org/transcripts/tasks/[id]/page.tsx, platform/components/events/suggest-event.tsx, platform/components/interactive-datetime.tsx, platform/components/label-events.tsx, platform/components/sessions/session.tsx, platform/components/task-box.tsx, platform/components/tasks/task-preview.tsx, platform/components/tasks/task.tsx, platform/components/thumbs.tsx, platform/models/models.ts
- Issue wrapping
- Lots of nested cards
- Better format of metadata in frontend
- Wrapping 
- GH workflow to autocreate PR to main
=> Feat: Adds go to Sessions and better card formatting

backend/app/api/platform/models/abtests.py, backend/app/services/mongo/explore.py, platform/app/org/ab-testing/[version_id]/page.tsx, platform/components/abtesting/abtesting-columns.tsx, platform/components/abtesting/abtesting-dataviz.tsx, platform/components/abtesting/abtesting.tsx, platform/components/sessions/session.tsx, platform/components/tasks/task.tsx, platform/models/models.ts
- Hard to keep track of versions ids 
- Dates in AB tests and when selecting AB tests
- Dates in AB tests table
- Better format of Messages
=> feat: Adds dates to AB tests

backend/app/api/platform/models/abtests.py, backend/app/services/mongo/explore.py, platform/app/org/ab-testing/[version_id]/page.tsx, platform/components/abtesting/abtesting-columns.tsx, platform/components/abtesting/abtesting-dataviz.tsx, platform/components/abtesting/abtesting.tsx, platform/components/sessions/session.tsx, platform/components/tasks/task.tsx, platform/models/models.ts
No Session metadata about last updated time
- Session.last_message_ts carries the latest Task.created_at
- Endpoint to recompute it on past data
- Fix sorting issue in AB tests
=> Feat: Adds Session.last_message_ts

backend/app/api/platform/endpoints/explore.py, backend/app/api/platform/models/explore.py, backend/app/services/mongo/explore.py, platform/components/abtesting/abtesting-dataviz.tsx, platform/components/abtesting/create-new-ab-test-button.tsx
You can select the events you want in AB-test.
- Zod form with checkbox in a dropdownMenu
- Add a parameter in the endpoint /ab-tests/compare-versions to filter on the selected events
=> feat: Select events in AB-test

backend/app/services/mongo/metadata.py, platform/components/filters.tsx, platform/components/tasks/tasks-table-columns.tsx, platform/components/users/users-table-columns.tsx, platform/components/users/users-table.tsx
Optimize the query so that users with a lot of events can still be processed
=> Fix: issue with filtering

platform/app/org/settings/account/page.tsx, platform/app/org/settings/project/page.tsx, platform/components/callouts/import-data.tsx, platform/components/copy-button.tsx, platform/components/sessions/session.tsx, platform/components/tasks/task.tsx, platform/components/users/users-table-columns.tsx
Created and upgraded the copy buttons on the platform
Multiple copy buttons, each slightly different and with no feedback on click 
Copy Button in /components
- [ x ] typing, linting, docstrings (cicd will fail)
=> feat: create copy component

platform/components/users/users-table-columns.tsx
=> style: adds back user ids 

phospho-python/phospho/models.py, platform/app/org/dataviz/studio/page.tsx, platform/components/dashboard/dashboard.tsx, platform/models/models.ts
Support for scoring_id in dashboard tiles
=> Adds scorer_id to dashboard tiles

platform/components/dataviz.tsx, platform/components/users/users-table-columns.tsx
=> feat: route to get users table in API v3

platform/components/sessions/sessions-table.tsx, platform/components/tasks/tasks-table.tsx, platform/components/ui/sheet.tsx, platform/components/users/users-table.tsx
You had to double click to preview another session, message, user
You can interact with the table below to switch quickly between session, messages, users
=> style: Keep side tabs open

platform/components/sessions/session.tsx, platform/components/sessions/sessions-table.tsx, platform/components/tasks/tasks-table.tsx, platform/components/ui/sheet.tsx, platform/components/users/users-table.tsx
## Before
You had to double click to preview another session, message, user
You can interact with the table below to switch quickly between session, messages, users
=> style: Keep side tabs open and allow to switch between rows

CONTRIBUTE.md, extractor/Dockerfile
=> fix: downgrade extractor

backend/app/services/mongo/users.py, platform/components/users/user-dataviz-pies.tsx, platform/components/users/users-dataviz.tsx
This improves the user tab with a retention graph
=> feat: create retention graph

backend/app/api/v3/endpoints/export.py, backend/tests/integration/python/test_onboarding.py
=> fix: comment the export analytics test

backend/app/services/mongo/users.py, platform/components/users/users-dataviz.tsx
Add tooltip to user retention graph and edit X axis values for better format
=> fix: UI for user retention

.github/workflows/phospho-python-test.yaml, backend/app/api/platform/models/explore.py, phospho-python/phospho/extractor.py, phospho-python/tests/test_log.py
Logging a list of {role:, content:} messages resulted in logging a string
- phospho.log supports lists in input, output
- The list has heuristics to support system prompt, multiple user messages, multiple assistant messages
- Tests run on 3.13
=> feat: Adds support for list of RoleContentMessages in phospho.log input and output

backend/app/api/v3/endpoints/log.py, backend/app/api/v3/models/log.py, backend/app/services/mongo/extractor.py, backend/notebooks/.gitignore, extractor/extractor/models/log.py, extractor/extractor/services/log/tasks.py, extractor/extractor/temporal/activities.py, extractor/extractor/temporal/workflows.py, extractor/main.py
The v3/log endpoint was not implemented.
=> fix: Log messages workflow

backend/app/services/log.py, backend/app/services/mongo/extractor.py, extractor/extractor/models/log.py, extractor/extractor/services/log/tasks.py, extractor/extractor/temporal/activities.py
fixes the platform error where the latest message date is not calculated
The extractor was not called when no need to run analytics
We always call the extractor to run the session pipeline without running analytics
=> fix: call session calculation in extractor without running analytics

backend/app/services/log.py, extractor/extractor/temporal/activities.py
=> fix: Clustering loading bar when no clustering ran

backend/app/services/mongo/dataviz.py, backend/app/services/mongo/explore.py, platform/components/dataviz-tagger.tsx
Breakdown by tagger_name and metric avg_scorer_value works
=> Fix: Breadown by tagger_name ; style: hover card 

backend/app/api/v2/endpoints/projects.py, backend/app/services/mongo/projects.py, backend/app/services/mongo/recipes.py, extractor/extractor/models/pipelines.py, extractor/extractor/temporal/activities.py
=> Fix: issue with eventdefinitions without recipes and remove deprecated code

backend/app/services/mongo/explore.py, backend/app/services/mongo/query_builder.py, platform/components/filters.tsx
Sessions metadata filters were implemented but not displayed
Display session metadata filters
=> Fix: issue with none values in event KPI ; fix: display session metadata filters

backend/app/api/platform/endpoints/recipes.py, backend/app/services/mongo/projects.py
=> feat: Enforce limit on recipe run

backend/app/services/mongo/sessions.py, phospho-python/phospho/lab/job_library.py, phospho-python/phospho/lab/language_models.py
=> chore: change fallback to gpt-4o-mini and better type check

backend/README.md, backend/app/api/platform/endpoints/projects.py, backend/app/services/mongo/projects.py, platform/README.md, platform/components/users/download-users.tsx, platform/components/users/users-table.tsx
There was a button to export tasks but not with user granularity
There is button in the users Table to export users data
=> Feat: Export users data

backend/app/api/platform/endpoints/projects.py, backend/app/api/platform/models/projects.py, backend/app/services/mongo/projects.py, platform/components/users/download-users.tsx
When there was no user in project data, the download button was sending empty files
If there are no user in a project, a toast appear and no email is sent
=> feat: Add filters to export users, handle edge case when no user

.github/workflows/phospho-python-test.yaml, backend/app/services/log.py, backend/app/services/mongo/projects.py
=> feat: Export users filters & failsafe when no users 

backend/app/services/integrations/postgresql.py
Users created but have no authorization over tables.
The existing authorization allowed user to connect, but not to read data.
Select role allows the user to query data.
=> fix: Update user management for sql db

.gitignore, backend/README.md, backend/app/api/v2/models/projects.py, backend/app/services/mongo/projects.py, backend/app/services/mongo/users.py, platform/components/label-events.tsx, platform/components/users/users-table-columns.tsx, platform/models/models.ts
There is a new button to export users data. The exported data contained a column 'events' which contained all the data from the class 'Event', the user query and system response included. 
Users data is now formatted differently. There is a column for each detected event with event_name as a header. The value is the number of occurrences.
=> FEAT :  Reformat Exported User Data

backend/app/services/mongo/dataviz.py, platform/components/dataviz-tagger.tsx, platform/components/dataviz.tsx
Despite being immutable, the SWR data was invalidated due to the accessToken refreshing. This resulted in multiple, concurrent API calls in Data Studio that caused heavy loads on the database. 
- Less duplicate API calls. 
- No recomputing of sessions length and task position
- Remove options to SWRImmutable (they are not used)
=> feat: Avoid duplicate API calls when token is refreshed in data studio

platform/components/abtesting/abtesting-dataviz.tsx
Fetch AB tests data only once and not every time accessToken is refreshed
=> fix: Switch AB test to immutable

backend/app/services/mongo/explore.py, platform/components/filters.tsx, platform/components/tasks/tasks-dataviz.tsx
=> fix: Optimize top 5 events, metadata values

backend/app/services/mongo/explore.py, platform/components/abtesting/abtesting-dataviz.tsx
- Less convoluted frontend
- Earlier filters for AB test query
- Don't merge "tasks" table (instead use the .task object attached to the events documents)
=> feat: Optimize AB test query

.github/workflows/backend-deploy-production.yml, docker-compose.yml
=> fix: Adds missing env variable in prod

platform/components/clusters/clusters.tsx
=> fix: Hide export clusterings for project with no clustering

.github/pull_request_template.md, examples/lab/parallel-calls.ipynb, internal-tools/cronemails/email_templates.py, phospho-python/README.md, phospho-python/docs/source/index.rst, phospho-python/phospho/main.py, phospho-python/pyproject.toml, platform/app/org/insights/events/page.tsx, platform/components/callouts/label-tasks.tsx, platform/components/callouts/setup-abtesting.tsx, platform/components/callouts/setup-users.tsx, platform/components/events/run-event.tsx, platform/components/navbar/help.tsx
=> Fix: edit more docs links
